apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collections.kabanero.io
spec:
  group: kabanero.io
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              desiredState:
                type: string
              name:
                type: string
              repositoryUrl:
                type: string
              version:
                type: string
            type: object
          status:
            properties:
              activeLocation:
                type: string
              activePipelines:
                items:
                  properties:
                    activeAssets:
                      items:
                        properties:
                          assetDigest:
                            type: string
                          assetName:
                            type: string
                          status:
                            type: string
                          statusMessage:
                            type: string
                        type: object
                      type: array
                    digest:
                      type: string
                    name:
                      type: string
                    url:
                      type: string
                  required:
                  - name
                  - url
                  - digest
                  type: object
                type: array
              activeVersion:
                type: string
              availableLocation:
                type: string
              availableVersion:
                type: string
              images:
                items:
                  properties:
                    id:
                      type: string
                    image:
                      type: string
                  type: object
                type: array
              status:
                type: string
              statusMessage:
                type: string
            type: object
  conversion:
    strategy: None
  names:
    kind: Collection
    listKind: CollectionList
    plural: collections
    singular: collection
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: CreationTimestamp is a timestamp representing the server time when
      this object was created. It is not guaranteed to be set in happens-before order
      across separate operations.
    name: Age
    type: date
  - JSONPath: .status.status
    description: Collection status.
    name: Status
    type: string

