packageName: kabanero-operator
channels:
- name: alpha
  currentCSV: kabanero-operator.v0.5.0
- name: release-0.3
  currentCSV: kabanero-operator.v0.3.5
- name: release-0.4
  currentCSV: kabanero-operator.v0.4.0
- name: release-0.5
  currentCSV: kabanero-operator.v0.5.0
- name: release-0.6
  currentCSV: kabanero-operator.v0.6.1
- name: release-0.7
  currentCSV: kabanero-operator.v0.7.0
- name: release-0.8
  currentCSV: kabanero-operator.v0.8.0
- name: release-0.9
  currentCSV: kabanero-operator.v0.9.2
defaultChannel: release-0.9

