apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.6.1"
  stacks: 
    repositories: 
    - name: central
      https:
        url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.3/kabanero-stack-hub-index.yaml
    pipelines:
    - id: default
      sha256: 50f5874147867813db7bef424f1567f904eaaffbcbc92aae56421e63cd13ee0f
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.1/default-kabanero-pipelines.tar.gz
